const fs = require('fs');
let lines = fs.readFileSync('src/App.tsx', 'utf8').split('\\n');

const newContent = [
  '  // Migrate legacy inventory to new products module',
  '  useEffect(() => {',
  '    if (menuProducts.length === 0 && inventoryComidas.length > 0) {',
  '      let nextCats = [...menuCategories];',
  '      let nextProds = [...menuProducts];',
  '',
  '      const addCategory = (name: string) => {',
  '        let cat = nextCats.find(c => c.name === name);',
  '        if (!cat) {',
  '          cat = { id: "CAT-" + Date.now() + Math.floor(Math.random()*1000), name, status: "activo" };',
  '          nextCats.push(cat);',
  '        }',
  '        return cat;',
  '      };',
  '',
  '      inventoryComidas.forEach(c => {',
  '        const cat = addCategory(c.category);',
  '        nextProds.push({',
  '          id: c.id,',
  '          name: c.name,',
  '          categoryId: cat.id,',
  '          category: cat.name,',
  '          description: c.ingredients',
  '            ?.map(i => inventoryItems.find(inv => inv.id === i.itemId)?.name)',
  '            .filter(Boolean).join(", ") || "Plato especial",',
  '          price: c.price || 0,',
  '          aplicaIva: true,',
  '          image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",',
  '          available: 0,',
  '          sold: 0,',
  '          status: "activo",',
  '          createdAt: new Date().toISOString(),',
  '          updatedAt: new Date().toISOString(),',
  '        });',
  '      });',
  '      inventoryBebidas.forEach(b => {',
  '        const cat = addCategory(b.category);',
  '        nextProds.push({',
  '          id: b.id,',
  '          name: b.name,',
  '          categoryId: cat.id,',
  '          category: cat.name,',
  '          description: `Bebida (${b.quantity} ${b.unit} stock)`,',
  '          price: parseFloat(b.price) || 0,',
  '          aplicaIva: true,',
  '          image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",',
  '          available: b.quantity,',
  '          sold: 0,',
  '          status: "activo",',
  '          createdAt: new Date().toISOString(),',
  '          updatedAt: new Date().toISOString(),',
  '        });',
  '      });',
  '      inventoryCombos.forEach(c => {',
  '        const cat = addCategory(c.category || "Combos");',
  '        nextProds.push({',
  '          id: c.id,',
  '          name: c.name,',
  '          categoryId: cat.id,',
  '          category: cat.name,',
  '          description: "Combo especial",',
  '          price: c.price || 0,',
  '          aplicaIva: true,',
  '          image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",',
  '          available: 0,',
  '          sold: 0,',
  '          status: "activo",',
  '          createdAt: new Date().toISOString(),',
  '          updatedAt: new Date().toISOString(),',
  '        });',
  '      });',
  '',
  '      setMenuCategories(nextCats);',
  '      setMenuProducts(nextProds);',
  '    }',
  '  }, [inventoryComidas, inventoryBebidas, inventoryCombos, menuProducts.length, menuCategories]);',
  '',
  '  // Generate menu items from inventory',
  '  const activeProducts = menuProducts.filter(p => p.status !== "inactivo");',
  '  const menuItems: MenuItem[] = activeProducts.map((p) => {',
  '    let dynamicAvailable = p.stock || 999;',
  '    const isComida = inventoryComidas.find((c) => c.id === p.id);',
  '    if (isComida) dynamicAvailable = calculateMaxComidas(isComida);',
  '    const isBebida = inventoryBebidas.find((b) => b.id === p.id);',
  '    if (isBebida) dynamicAvailable = isBebida.quantity;',
  '    const isCombo = inventoryCombos.find((c) => c.id === p.id);',
  '    if (isCombo) dynamicAvailable = calculateMaxCombos(isCombo);',
  '',
  '    return {',
  '      ...p,',
  '      available: dynamicAvailable,',
  '    };',
  '  });'
].join('\\n');

lines.splice(284, 41, newContent);
fs.writeFileSync('src/App.tsx', lines.join('\\n'));
